name: Java 17 Maven CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin   # Eclipse Temurin is a reliable OpenJDK build
          java-version: 17
          cache: maven

      # Build with Maven
      - name: Build with Maven
        run: mvn -B clean verify
